### ISSUE TITLE
projekt graficzny

### ISSUE THREAD

**Issue by domi-nika60** [domi-nika60/Liczydlo-naukowe#11]
projekt aplikacji

**Comment by domi-nika60** [comment]
czy może to być w paincie mój development team'ie?

**Comment by kuraczak** [comment]
oczywiście, może być nawet w notatniku, byle wiedzielibyśmy jak projektować ;)

**Comment by kuraczak** [comment]
wstaw go potem tutaj

**Comment by paaweel** [comment]
Mi na przyklad podoba sie cos takiego

![calcbot](https://cloud.githubusercontent.com/assets/22177988/26207680/821dba52-3be8-11e7-891f-99866d0a1830.png)

albo prosciej, takiego:

![ios-7-calci-2-image](https://cloud.githubusercontent.com/assets/22177988/26207768/bd980e66-3be8-11e7-9c61-5f0b6b5602ea.png)

Do tego mozna zrobic wyskakujace okienko z wykresem lub na dobra sprawe czymkolwiek.

**Comment by domi-nika60** [comment]
Macie to w dwóch miejscach :)

![kalkulator](https://cloud.githubusercontent.com/assets/28627914/26223794/ef09d34e-3c1f-11e7-8a80-de2deb0682e7.png)
